# Generated by Django 2.0.2 on 2018-03-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='foto'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='estatura',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
